- 我们通常会使用的是列向量
- 但是下面我们首先来描述如何用python描述行向量
$\left[\begin{array}{lll}4 & 5 & 7\end{array}\right]$

In [1]:
import numpy as np
a = np.array([4,5,7])
print(a)

[4 5 7]


- 遗憾的是，可以发现numpy默认是行向量，那么如何将其变为列向量呢，转置（transpose）方法对行向量无法起到应有的作用
- 我们可以将行向量看到是$1\times m$的特殊矩阵，采用\[[]\](二维数组初始化)方法来生成

In [5]:
a = np.array([[4,5,7]])
print(a.T)

[[4]
 [5]
 [7]]


- 向量加法和减法以及数乘不多叙述，下面讲一下内积(np.dot)

In [11]:
u = np.array([3,5,2])
v = np.array([1,4,7])
print(np.dot(u,v))

[3 5 2]
[1 4 7]
37


- 但是你会发现下面的代码却会报错,这种表示方法本质上是一个矩阵，只不过是行数或者列数为1的特殊矩阵罢了，将这种方法表示下的向量作为内积运算就需要符合矩阵的运算法则

In [15]:
u = np.array([[3,5,2]]).T
v = np.array([[1,4,7]]).T
print(np.dot(u,v))

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

- 外积运算$u\times v = |u||v|sin\theta$(np.cross)

In [18]:
u = np.array([3,3,9])
v = np.array([1,4,12])
print(np.cross(u,v))

[  0 -27   9]
