矩阵的表示

In [1]:
import numpy as np
a = np.array([[1,2],
[3,4],
[5,6],
[7,8]])
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


零矩阵

In [2]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

对角矩阵

In [3]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

单位矩阵

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])